apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-7s-dev
  # namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ekpicha/Test-7Solutions.git'
    targetRevision: main
    path: task-3-kustomize/flex/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
