apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
spec:
  replicas: 2 # changed
  template:
    spec:
      containers:
      - name: go-app
        image: "ekpicha/assignment-7s:20251018"